
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INTexp : aexpaexp : termoaexp : aexp '+' termoaexp : aexp '-' termotermo : INTtermo : termo '*' INTtermo : termo '/' INT"
    
_lr_action_items = {'INT':([0,5,6,7,8,],[4,4,4,11,12,]),'$end':([1,2,3,4,9,10,11,12,],[0,-1,-2,-5,-3,-4,-6,-7,]),'+':([2,3,4,9,10,11,12,],[5,-2,-5,-3,-4,-6,-7,]),'-':([2,3,4,9,10,11,12,],[6,-2,-5,-3,-4,-6,-7,]),'*':([3,4,9,10,11,12,],[7,-5,7,7,-6,-7,]),'/':([3,4,9,10,11,12,],[8,-5,8,8,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'aexp':([0,],[2,]),'termo':([0,5,6,],[3,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> aexp','exp',1,'p_exp','mathexp_parser.py',6),
  ('aexp -> termo','aexp',1,'p_aexp_termo','mathexp_parser.py',10),
  ('aexp -> aexp + termo','aexp',3,'p_aexp_add','mathexp_parser.py',14),
  ('aexp -> aexp - termo','aexp',3,'p_aexp_sub','mathexp_parser.py',18),
  ('termo -> INT','termo',1,'p_termo_INT','mathexp_parser.py',22),
  ('termo -> termo * INT','termo',3,'p_termo_mult','mathexp_parser.py',26),
  ('termo -> termo / INT','termo',3,'p_termo_div','mathexp_parser.py',30),
]
